### ISSUE TITLE
makin changes

### ISSUE THREAD

**Issue by vingard** [vingard/liveturtle#1]
hey use this repo for the socket version and this one (https://github.com/QuartzShard/Turtle-Client-and-server) for ftp.

i've made a couple of branches that we will need, feel free to make some more. also when raj accepts the contributor thing someone send him this.

**Comment by QuartzShard** [comment]
Just when I pushed a huge amount of changes to the other repo lol

**Comment by QuartzShard** [comment]
I've pushed them to cleanup and created a pull request, if Someone else wants to check it out and resolve the conflicts
