### ISSUE TITLE
reset button unresponsive when turtle display inactive

### ISSUE THREAD

**Issue by vingard** [vingard/liveturtle#4]
this is caused by the hacky way we do the turtle, we can't change how the display is unresponsive, however we might want to try disassociating the reset button from the display program. we could just close and reopen the display program and delete all files in /display/ to reset it from another program called reset.py.

**Comment by QuartzShard** [comment]
This is fixed in refreshbutton, due to the lack of while loop. Not the best solution, but it works

**Comment by QuartzShard** [comment]
Also fixed in Threaded due to moving over to the server- see pull request and try it for yourself

**Comment by vingard** [comment]
fixed
